[project]
name = "repl-nix-convert"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.14.0",
    "moviepy>=1.0.3",
    "youtube-dl>=2021.12.17",
    "yt-dlp>=2024.11.4",
]
